add_test( main.case_1 /home/fellicienta/GH/pr/build-max-crossing-point/Test [==[--gtest_filter=main.case_1]==] --gtest_also_run_disabled_tests)
set_tests_properties( main.case_1 PROPERTIES WORKING_DIRECTORY /home/fellicienta/GH/pr/build-max-crossing-point)
add_test( main.case_2 /home/fellicienta/GH/pr/build-max-crossing-point/Test [==[--gtest_filter=main.case_2]==] --gtest_also_run_disabled_tests)
set_tests_properties( main.case_2 PROPERTIES WORKING_DIRECTORY /home/fellicienta/GH/pr/build-max-crossing-point)
add_test( main.case_3 /home/fellicienta/GH/pr/build-max-crossing-point/Test [==[--gtest_filter=main.case_3]==] --gtest_also_run_disabled_tests)
set_tests_properties( main.case_3 PROPERTIES WORKING_DIRECTORY /home/fellicienta/GH/pr/build-max-crossing-point)
add_test( main.empty_set /home/fellicienta/GH/pr/build-max-crossing-point/Test [==[--gtest_filter=main.empty_set]==] --gtest_also_run_disabled_tests)
set_tests_properties( main.empty_set PROPERTIES WORKING_DIRECTORY /home/fellicienta/GH/pr/build-max-crossing-point)
set( Test_TESTS main.case_1 main.case_2 main.case_3 main.empty_set)
